name: auto build foss snapshot image
on:
  workflow_dispatch:
  schedule:
    - cron: "00 16 * * 2,6"

jobs:
  call-build-foss-snapshot:
    permissions:
      contents: write
    uses:
      ./.github/workflows/foss_snapshot.yml
              
