name: build nss snapshot with kmod
on: workflow_dispatch
env:
  SOURCE_REPO:  "https://github.com/openwrt/openwrt.git"
  SOURCE_BRANCH: "main"
  SCRIPT_REPO: "https://github.com/arix00/openwrt-mx4300.git"
  SCRIPT_BRANCH: "build"
  SCRIPT_INIT: "init_build.sh"
  
  BUILD_TYPE:  "nss"
  BUILD_VER: "snapshot"
  
jobs:
    build:
        name: build nss snapshot with kmod
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Install packages
              run: |
                  sudo apt-get update && \
                  sudo apt-get install -y \
                      build-essential \
                      clang \
                      flex \
                      bison \
                      g++ \
                      gawk \
                      gcc-multilib \
                      g++-multilib \
                      gettext \
                      git \
                      libncurses-dev \
                      libssl-dev \
                      python3-setuptools \
                      rsync \
                      unzip \
                      zlib1g-dev \
                      file \
                      jq \
                      wget && \
                  sudo apt-get clean

            - name: Prepare source code
              run:  |
                    git clone $SOURCE_REPO --branch $SOURCE_BRANCH .
                    git clone $SCRIPT_REPO --branch $SCRIPT_BRANCH $SCRIPT_BRANCH
                    cp $SCRIPT_BRANCH/script/*.sh .
                    rm -rf $SCRIPT_BRANCH
                    sh $SCRIPT_INIT $BUILD_TYPE $BUILD_VER                

            - name: Update feeds
              run:  scripts/feeds update -a && scripts/feeds install -a
            
            - name: Generate config
              run:  sh genconfig_nss.sh full

            - name: Build firmware images
              run:  make -j$(($(nproc)+1)) world
            
            - name: Check build version
              run:  cat `find staging_dir -name banner`

            - name: Prepare release
              run:  sh release_nss.sh

            - name: Release
              uses: ncipollo/release-action@v1
              with:
                tag: qualcommax-nss-$BUILD_VER-${{ env.build_id }}
                artifacts: release/*
                bodyFile: note.md

